{.warning[UnusedImport]: off.}
{.hint[XDeclaredButNotUsed]: off.}
import collections/rangeset
import collections/segtree_beats
import collections/hashtable
import collections/avltreenode
import collections/range_reverse_array_monoid
import collections/bitset
import collections/slopetrick
import collections/unionfind
import collections/segtree2d
import collections/group_unionfind
import collections/segtree
import collections/waveletmatrix
import collections/range_reverse_array
import collections/raw_ptr_avlset
import collections/persistent_segtree
import collections/SWAG
import collections/persistent_array
import collections/lazysegtree
import collections/root_rangesum
import collections/lichaotree
import collections/deletable_heapqueue
import collections/staticRMQ
import collections/tatyamset
import collections/avlset
import collections/segtree_var
import collections/rollback_unionfind
import collections/ppunionfind
import collections/persistent_unionfind
import collections/binary_trie
import collections/QSWAG
import collections/avltreenode_old
import collections/segtree_beats_template
import collections/staticbitset
import collections/wordsizetree
import collections/staticrangecount
import collections/persistent_binary_trie
import collections/weightedunionfind
import collections/topk_sum_heapq
import collections/range_reverse_dualsegtree
import collections/hashset
import collections/range_reverse_lazysegtree
import collections/defaultdict
import collections/avlset_old
import collections/fenwick2d
import collections/rootvalue_unionfind
import collections/bitvector
import geometry/argsort
import geometry/intersect
import geometry/angle
import geometry/polygon
import geometry/base
import geometry/ccw
import geometry/distance
import geometry/projection
import convolution/xor_convolution
import convolution/ntt
import convolution/convolution
import modint/modint
import modint/exp_modint
import modint/montgomery_impl
import modint/barrett_impl
import graph/bipartite_graph
import graph/tsp
import graph/steiner_tree
import graph/namori_graph
import graph/restore_shortest_path_from_prev
import graph/topologicalsort
import graph/graph
import graph/namori_forest
import graph/reverse_edge
import graph/functional_graph
import graph/dijkstra
import graph/warshall_floyd
import graph/range_edge_graph
import graph/graph_debug
import graph/SCC
import graph/bellmanford
import graph/dag_minimum_path_cover
import graph/dynamic_bipartite
import graph/grid_to_graph
import graph/maxk_dijkstra
import graph/merge_tree
import graph/kruskal
import str/palindromic_tree
import str/can_reverse_hash_string
import str/zalgorithm
import str/hash_string
import str/manacher
import str/lcp_naive
import str/compressed_trie
import str/merged_static_string
import str/rolling_hash
import str/lcs
import str/static_string
import str/run_length_encode
import tree/cartesiantree
import tree/diameter
import tree/rerooting
import tree/heavylightdecomposition
import tree/prufer
import utils/random_helper
import utils/binary_search
import utils/bititers
import utils/memo
import utils/knapsack
import utils/implicit_dijkstra
import utils/constants
import utils/seqidx
import utils/sequtils2D
import utils/cumsum2d
import utils/kth_element
import utils/list_procs
import utils/inversion_number
import utils/imos2d
import utils/lis
import utils/mo
import utils/gridutils
import utils/itertools
import utils/grid_searcher
import matrix/static_matrix
import matrix/matops
import matrix/matrix
import matrix/rolling_hash_2d
import tmpl/citrus
import tmpl/optimize
import tmpl/qcfium
import tmpl/sheep
import math/divisor
import math/euler_phi
import math/sqrt_heuristic_for_floor_sum
import math/powmod
import math/baser
import math/float128
import math/stern_brocot_tree
import math/isqrt
import math/nearest_equiv
import math/xor_basis
import math/int128
import math/isprime
import math/ext_gcd
import math/inv_gcd
import math/mex_naive
import math/inner_math
import math/primitive_root
import math/primefactor
import math/combination_prefix_sum
import math/combination_int
import math/osa_k
import math/fractions
import math/combination
