name: deploy-doc

on:
  workflow_run:
    workflows: ["verify"]
    types:
        - completed

jobs:
  deploy-doc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: gh-pages

      - name: Copy and Push
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.email "<EMAIL>"
          git config --global user.name "GitHub Action"
          git checkout gh-pages
          cp -rf srd/* .
          git add -A
          "[workflow] copy docs $(git rev-parse HEAD~1)"
          git push "https://${{ secrets.GH_PAT }}@github.com/kemuniku/cplib.git" gh-pages
