name: deploy-doc

on:
  workflow_run:
    workflows: ["verify"]
    types: [completed]
    branches: ["main"]

jobs:
  deploy-doc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: gh-pages

      - name: Build Nimdoc
        run: |
          git fetch origin && git checkout main
          cd tools
          make clean && make build_nimdoc.o
          ./build_nimdoc.o
          cd ../src/cplib
          git add nimdoc
          git stash push nimdoc
          git checkout gh-pages
          git stash pop stash@{0}
          git add nimdoc
          if ! git diff --exit-code --quiet
          then
            git commit && git push
          fi

      - name: Copy and Push
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.email "<EMAIL>"
          git config --global user.name "GitHub Action"
          git checkout gh-pages
          cp -rf src/* .
          git add -A
          git diff --quiet && git diff --staged --quiet || git commit -am "[workflow] copy docs $(git rev-parse HEAD~1)"
          git push "https://${{ secrets.GH_PAT }}@github.com/kemuniku/cplib.git" gh-pages
