name: verify

on:
  push:
    branches:
    - main
  pull_request:
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest

    permissions:
      actions: write
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: pip3 install -U online-judge-verify-helper

      - name: Cache choosenim
        id: cache-choosenim
        uses: actions/cache@v4
        with:
          path: ~/.choosenim
          key: ${{ runner.os }}-choosenim-stable

      - name: Cache nimble
        id: cache-nimble
        uses: actions/cache@v4
        with:
          path: ~/.nimble
          key: ${{ runner.os }}-nimble-stable

      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: 1.6.14

      - name: Install Dependency
        id: install-dependency
        run: nimble install https://github.com/zer0-star/Nim-ACL -N

      - name: Restore Verify Cache
        id: restore-verify-cache
        uses: actions/cache/restore@v4
        with:
          path: src/.verify-helper/cache
          key: ${{ runner.os }}-verify-cases-${{ github.sha }}
          restore-keys: ${{ runner.os }}-verify-cases-

      - name: Get dropbox token
        env:
          DROPBOX_REFRESH_TOKEN: ${{ secrets.DROPBOX_REFRESH_TOKEN }}
          DROPBOX_APP_KEY: ${{ secrets.DROPBOX_APP_KEY }}
          DROPBOX_APP_SECRET: ${{ secrets.DROPBOX_APP_SECRET }}
        run:  |
          {
            echo 'DROPBOX_TOKEN<<EOF'
            curl --silent https://api.dropbox.com/oauth2/token \
            --user ${DROPBOX_APP_KEY}:${DROPBOX_APP_SECRET} \
            --data grant_type=refresh_token \
            --data refresh_token=${DROPBOX_REFRESH_TOKEN} \
            | jq -r .access_token
            echo EOF
          } >> "$GITHUB_ENV"

      - name: Remove init.sh
        run: rm -f init.sh

      - name: Run tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          YUKICODER_TOKEN: ${{ secrets.YUKICODER_TOKEN }}
          GH_PAT: ${{ secrets.GH_PAT }}
        run: cd src && oj-verify all -j 4 --tle 10

      - name: Clear Verify Cache
        if: always()
        id: clear-verify-cache
        run: |
          gh extension install actions/gh-actions-cache
          REPO=${{ github.repository }}
          cacheKeys=$(gh actions-cache list -R $REPO --key ${{ runner.os }}-verify-cases | cut -f 1 )
          set +e
          for cacheKey in $cacheKeys
          do
            echo "Deleting caches... $cacheKey"
            gh actions-cache delete $cacheKey -R $REPO --confirm
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Save Verify Cache
        if: always()
        id: same-verify-cache
        uses: actions/cache/save@v4
        with:
          path: src/.verify-helper/cache
          key: ${{ runner.os }}-verify-cases-${{ github.sha }}
